# Local production testing environment
# Privacy-first, stateless architecture

version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
      - LOG_LEVEL=WARNING
      - MAX_SESSION_AGE=7200
      - ALLOWED_HOSTS=localhost,127.0.0.1,backend,frontend,0.0.0.0,*.github.dev,*.app.github.dev,*.render.com
      - ALLOWED_ORIGINS=http://localhost,http://localhost:80,https://localhost,http://frontend:80,https://*.github.dev,https://*.app.github.dev
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
      - VITE_API_URL=http://backend:8000
    restart: unless-stopped

networks:
  default:
    name: prophet-web-prod