# Testing environment for Prophet Web Interface
# Privacy compliance and functionality testing

version: '3.8'

services:
  backend-test:
    build: ./backend
    environment:
      - ENVIRONMENT=test
      - LOG_LEVEL=DEBUG
      - MAX_SESSION_AGE=300  # 5 minutes for testing
      - ALLOWED_HOSTS=localhost,127.0.0.1,backend,frontend,backend-test,frontend-test,0.0.0.0,*.github.dev,*.app.github.dev,*.render.com,testserver
      - ALLOWED_ORIGINS=http://localhost:3001,http://127.0.0.1:3001,http://frontend:80,https://*.github.dev,https://*.app.github.dev
    command: pytest tests/ -v --cov=src --cov-report=term-missing
    volumes:
      - ./backend:/app
    depends_on:
      - backend

  frontend-test:
    build: ./frontend
    environment:
      - NODE_ENV=test
      - VITE_API_URL=http://backend:8000
    command: npm test
    volumes:
      - ./frontend:/app
    depends_on:
      - frontend

  e2e-test:
    build: ./frontend
    environment:
      - NODE_ENV=test
      - PLAYWRIGHT_BROWSERS_PATH=/ms-playwright
      - VITE_API_URL=http://backend:8000
    command: npm run test:e2e
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
      - frontend

  backend:
    build: ./backend
    ports:
      - "8001:8000"
    environment:
      - ENVIRONMENT=test
      - LOG_LEVEL=DEBUG
      - MAX_SESSION_AGE=7200
      - ALLOWED_HOSTS=localhost,127.0.0.1,backend,frontend,backend-test,frontend-test,e2e-test,0.0.0.0,*.github.dev,*.app.github.dev,*.render.com,testserver
      - ALLOWED_ORIGINS=http://localhost:3001,http://127.0.0.1:3001,http://frontend:80,https://*.github.dev,https://*.app.github.dev

  frontend:
    build: ./frontend
    ports:
      - "3001:80"
    depends_on:
      - backend
    environment:
      - NODE_ENV=test
      - VITE_API_URL=http://backend:8000

networks:
  default:
    name: prophet-web-test