services:
  # Backend API Service - Prophet Processing
  - type: web
    name: prophet-web-backend
    runtime: python
    buildCommand: "cd backend && pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "cd backend && uvicorn src.main:app --host 0.0.0.0 --port $PORT --workers 1 --access-log --log-level info"
    plan: starter  # Can upgrade to standard/pro for more memory and CPU
    region: frankfurt
    branch: main
    buildFilter:
      paths:
        - backend/**
        - render.yaml
      ignoredPaths:
        - "*.md"
        - ".git/**"
        - ".kiro/**"
    
    # No persistent disk for Hobby tier; use ephemeral /tmp
    # Environment variables
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: $PORT  # Render provides this automatically
      
      # Session settings
      - key: MAX_SESSION_AGE
        value: 7200  # 2 hours in seconds
      - key: MAX_MEMORY_MB
        value: 512   # Memory limit for stateless processing
      - key: AUTO_CLEANUP_INTERVAL
        value: 300   # 5 minutes cleanup interval
      
      # Application settings
      - key: SECRET_KEY
        generateValue: true  # Render generates secure random key
      - key: ALLOWED_ORIGINS
        value: https://prophet-web-frontend.onrender.com
      
      # File upload limits
      - key: MAX_FILE_SIZE_MB
        value: 50
      - key: MAX_CONCURRENT_UPLOADS
        value: 5
      
      # Performance settings
      - key: WORKER_TIMEOUT
        value: 300  # 5 minutes for long forecasts
      - key: MAX_CONCURRENT_FORECASTS
        value: 3
      
      # Logging
      - key: LOG_LEVEL
        value: INFO
      - key: LOG_FORMAT
        value: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    
    # Health check for automatic restarts
    healthCheckPath: /health

    # Auto-deploy settings
    autoDeploy: true
    
  # Frontend Static Site - Web Interface
  - type: web
    name: prophet-web-frontend
    runtime: static
    buildCommand: "cd frontend && npm ci && npm run build"
    staticPublishPath: frontend/dist
    branch: main
    buildFilter:
      paths:
        - frontend/**
        - render.yaml
      ignoredPaths:
        - "*.md"
        - ".git/**"
        - ".kiro/**"
    
    # Frontend environment variables
    envVars:
      - key: VITE_API_URL
        value: https://prophet-web-backend.onrender.com
      - key: VITE_ENVIRONMENT
        value: production
      - key: VITE_APP_NAME
        value: Prophet Web Interface
      - key: VITE_APP_MODE
        value: production
    
    # Security headers
    headers:
      # Prevent embedding in frames
      - path: /*
        name: X-Frame-Options
        value: DENY
      
      # Prevent MIME type sniffing
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      
      # Strict referrer policy
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
      
      # Content Security Policy
      - path: /*
        name: Content-Security-Policy
        value: "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; connect-src 'self' https://prophet-web-backend.onrender.com; font-src 'self'"
      
      # Prevent caching of sensitive pages
      - path: /
        name: Cache-Control
        value: no-cache, no-store, must-revalidate
      
      # Permissions policy
      - path: /*
        name: Permissions-Policy
        value: geolocation=(), microphone=(), camera=(), payment=(), usb=(), magnetometer=(), gyroscope=(), accelerometer=()
    
    # Auto-deploy settings
    autoDeploy: true