[tool.ruff]
# Match Black’s line length and target version
line-length = 88
target-version = "py38"

# Files to include/exclude
include = ["*.py", "*.pyi"]
exclude = [
  ".git",
  ".hg",
  ".mypy_cache",
  ".tox",
  ".venv",
  "venv",
  "build",
  "dist",
  ".eggs"
]

[tool.ruff.format]
# Use Ruff’s formatter (Black-compatible)
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.ruff.lint]
# Enable rulesets that approximate Pylint + Black + isort
select = [
  "E",   # pycodestyle (PEP8)
  "W",   # Warning (pycodestyle)
  "F",   # pyflakes, Flake8
  "I",   # isort (imports)
  "N",   # pep8-naming
  "D",   # pydocstyle 
  "B",   # flake8-bugbear
  "C90", # mccabe (complexity)
  "PL",  # pylint-like rules
]
ignore = [
  "E203", # whitespace before ':' (Black-compatible)
  "E501", # line length (handled by formatter)
]

[tool.ruff.lint.isort]
# Import sorting style compatible with Black
combine-as-imports = true
force-single-line = false
force-sort-within-sections = true

[tool.ruff.lint.mccabe]
# Similar to Pylint’s max-complexity=10
max-complexity = 10
