[tool.ruff]
# Match Black’s line length and target version
line-length = 88
target-version = "py38"

# Files to include/exclude
include = ["*.py", "*.pyi"]
exclude = [
  ".git",
  ".hg",
  ".mypy_cache",
  ".tox",
  ".venv",
  "venv",
  "build",
  "dist",
  ".eggs"
]

# Use Ruff’s formatter (Black-compatible)
[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.ruff.lint]
# No need to ignore W503 (Ruff doesn’t have it)
# E203 is already off by default, but you can list it anyway
ignore = ["E203"]

[tool.ruff.lint.isort]
# Import sorting style compatible with Black
combine-as-imports = true
force-single-line = false
