name: Deployment Configuration Validation

on:
  workflow_dispatch:

jobs:
  validate-deployment-config:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Validate deployment configuration
        run: python scripts/test_deployment_config.py
      - name: Validate render.yaml syntax
        run: python -c "import yaml; yaml.safe_load(open('render.yaml'))"
      - name: Check backend requirements
        run: pip install -r backend/requirements.txt --dry-run
      - name: Check frontend dependencies
        run: npm ci --prefix frontend --dry-run
      - name: Validate environment variables
        run: |
          # Check that all required environment variables are documented
          for var in ENVIRONMENT SECRET_KEY MAX_SESSION_AGE VITE_API_URL; do
            grep -q "$var" .env.example || (echo "Error: $var not found in .env.example" && exit 1)
          done
          echo "✓ Environment variables validated"

  validate-code-privacy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Run privacy check
        run: python scripts/validate_deployment.py
  
  validate-render-config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      - name: Install dependencies
        run: pip install pyyaml
      - name: Validate Render configuration
        run: python scripts/validate_render_deployment.py

  summary:
    runs-on: ubuntu-latest
    needs: [validate-deployment-config, validate-code-privacy, validate-render-config]
    steps:
      - name: Summary
        run: |
          echo "✅ Deployment configuration validation completed successfully"
          echo "✅ Privacy compliance verified"
          echo "✅ Security headers configured"
          echo "✅ Ready for Render deployment"